language: python
matrix:
  include:
    - os: linux
      dist: xenial   # required for Python >= 3.7
      python: 3.7
    - os: osx
      osx_image: xcode11.3
      language: shell  # 'language: python' is an error on Travis CI macOS
      before_install:
      - |
        # brew update
        brew unlink python@2
        brew install libusb
        brew install python@3
    - os: windows
      language: shell  # 'language: python' is an error on Travis CI windows 
      env: >-
        PATH=/c/Python37:/c/Python37/Scripts:$PATH      
      before_install:
        - choco install python --version=3.7.6
        - cp /c/Python37/python.exe /c/Python37/python3.exe
addons:
  apt:
    pacakges:
      - libusb-1.0-0-dev
install:
  - pip3 install -r requirements.txt
  - python3 setup.py build_ext --inplace
script:
  - python3 -m unittest
  - python3 setup.py sdist
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then python3 setup.py bdist_wheel; fi
